name: freeflow.ourworld.tf
on:
  push:
    branches: [ master ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest change on freeflow.ourworld.tf
      uses: appleboy/ssh-action@master
      with:
        host: freeflow.ourworld.tf
        username: webuser
        key: ${{ secrets.TF_SECRET }}
        port: 34022
        script: |
          cd websites/tmp/www_freeflownation/
          git log -1
          git fetch
          git reset --hard origin/master
          sed -i "s/https:\/\/www2.freeflow.ourworld.tf/https:\/\/freeflow.ourworld.tf/g" config.toml
          ./build.sh
